name: Release
on:
  push:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short
  # RUSTFLAGS: '-D warnings -W unreachable-pub -W rust-2021-compatibility'
  # RUSTFLAGS: '-W unreachable-pub -W rust-2021-compatibility'
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          cache-on-failure: true

      - name: Git Semantic Version
        # You may pin to the exact commit or the version.
        # uses: Hathoute/semantic-version@3039ecb9dc6bb3a84585cc13e930dca19d9924c8
        uses: PaulHatch/semantic-version@v5.0.3
        id: semver
        with:
          enable_prerelease_mode: true

      - name: Update Version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "0.0.1"
          replace: ${{ steps.semver.outputs.version_tag }}
          include: "src-tauri/config.tauri.json"
          regex: false
  
      - name: Build the app
        uses: tauri-apps/tauri-action@refactor

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ steps.semver.outputs.version_tag }}
          releaseName: 'XBHive Manager v__VERSION__'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: false
          prerelease: true
